/*
 * For commercial customers of Moderne Inc., this repository is licensed per the terms of our contract.
 * For everyone else, this is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
 * See: https://creativecommons.org/licenses/by-nc-sa/4.0/
 */
lexer grammar JCLLexer;

UTF_8_BOM : '\uFEFF' -> skip;

WS : [ \t\f;]+ -> channel(HIDDEN);
EOL : (CR? LF | FORM_FEED) -> channel(HIDDEN);

JCL_STATEMENT : ('^^JCL_STATEMENT^^' | '^^JCL^^') -> skip, pushMode(INSIDE_JCL);
JCL_CONT : '^^JCL_CONT^^//' -> pushMode(INSIDE_JCL);

JCL_STREAM : ('^^STREAM^^' | '^^STREAM_END^^') -> skip, pushMode(INSIDE_STREAM);

JES2 : ('^^JES2^^' | '^^JES2_CONT^^') -> skip, pushMode(INSIDE_JES2);
JES3 : ('^^JES3^^' | '^^JES3_CONT^^') -> skip, pushMode(INSIDE_JES3);
CM : '^^CM^^' -> skip, pushMode(INSIDE_CM);
COMMENT : '^^COMMENT^^' -> skip, pushMode(INSIDE_COMMENT);
UNKNOWN : '^^UNKNOWN^^' -> skip, pushMode(INSIDE_UNKNOWN);

CA_START : '^^CA_START^^';
STRINGLITERAL
    : '"' (~["\n\r] | '""' | '\'' | '`')* '"'
    | '\'' (~['\n\r] | '\'\'' | '"' |'`')* '\''
    | '`' (~['\n\r] | '``' | '"' | '\'')* '`'
    ;

TEXT : ~[ \r\n^'"]+ | '^' | '\'' | '"';

fragment LF : '\n';
fragment CR : '\r';
fragment FORM_FEED : '\u000C';

mode INSIDE_JCL;
JCL_WS : WS -> type(WS), channel(HIDDEN);
JCL_EOL : EOL -> type(EOL), channel(HIDDEN), popMode;

JCL_IF : 'IF' -> pushMode(IF_CONDITION);
JCL_TC_START : '^^TC_START^^' -> pushMode(INSIDE_TRAILING_COMMENT);
JCL_CA_START : CA_START;

// keywords
JCL_CNTL : 'CNTL';
JCL_DATASET : 'DATASET';
JCL_DD : 'DD';
JCL_ELSE : 'ELSE';
JCL_ENDCNTL : 'ENDCNTL';
JCL_ENDDATASET : 'ENDDATASET';
JCL_ENDIF : 'ENDIF';
JCL_ENDPROCESS : 'ENDPROCESS';
JCL_EXEC : 'EXEC';
JCL_EXPORT : 'EXPORT';
JCL_FORMAT : 'FORMAT';
JCL_INCLUDE : 'INCLUDE';
JCL_JCLLIB : 'JCLLIB';
JCL_JOB : 'JOB';
JCL_JOBPARM : 'JOBPARM';
JCL_MAIN : 'MAIN';
JCL_MESSAGE : 'MESSAGE';
JCL_NET : 'NET';
JCL_NETACCT : 'NETACCT';
JCL_NOTIFY : 'NOTIFY';
JCL_OPERATOR : 'OPERATOR';
JCL_OUTPUT : 'OUTPUT';
JCL_PAUSE : 'PAUSE';
JCL_PEND : 'PEND';
JCL_PRIORITY : 'PRIORITY';
JCL_PROC : 'PROC';
JCL_PROCESS : 'PROCESS';
JCL_ROUTE : 'ROUTE';
JCL_SCHEDULE : 'SCHEDULE';
JCL_SET : 'SET';
JCL_SETUP : 'SETUP';
JCL_SIGNOFF : 'SIGNOFF';
JCL_SIGNON : 'SIGNON';
JCL_THEN : 'THEN';
JCL_XEQ : 'XEQ';
JCL_XMIT : 'XMIT';

JCL_PARAMETER
    : JCL_ACCODE | JCL_ACCT | JCL_ADDRESS | JCL_ADDRSPC | JCL_AFF | JCL_AMP | JCL_AVGREC
    | JCL_BLKSIZE | JCL_BLKSZLIM | JCL_BUFND | JCL_BUFNI | JCL_BUFNO | JCL_BUFSP | JCL_BUILDING | JCL_BURST | JCL_BYTES
    | JCL_CCSID | JCL_CHARS | JCL_CHKPT | JCL_CKPTLINE | JCL_CKPTPAGE | JCL_CKPTSEC | JCL_CLASS | JCL_CNTL
    | JCL_COLORMAP | JCL_COMMAND | JCL_COMPACT | JCL_COMSETUP | JCL_COND | JCL_CONTROL | JCL_COPIES | JCL_CROPS
    | JCL_DATA | JCL_DATACK | JCL_DATACLAS | JCL_DCB | JCL_DDNAME | JCL_DEFAULT | JCL_DEN | JCL_DEPT | JCL_DEST | JCL_DISP | JCL_DLM
    | JCL_DPAGELBL | JCL_DSN | JCL_DSNTYPE | JCL_DSORG | JCL_DUMMY | JCL_DUPLEX | JCL_DYNAMNBR
    | JCL_ENDCNTL | JCL_EXEC | JCL_EXPDT
    | JCL_FCB | JCL_FILEDATA | JCL_FLASH | JCL_FORMDEF | JCL_FORMLEN | JCL_FORMS | JCL_FREE
    | JCL_GROUP | JCL_GROUPID
    | JCL_HOLD
    | JCL_IF | JCL_THEN | JCL_ELSE | JCL_ENDIF
    | JCL_INDEX
    | JCL_JCLLIB | JCL_JESDS | JCL_JOB | JCL_JOBCAT | JCL_JOBLIB
    | JCL_KEYOFF
    | JCL_LABEL | JCL_LGSTREAM | JCL_LIKE | JCL_LINDEX | JCL_LINECT | JCL_LINES | JCL_LRECL
    | JCL_MEMLIMIT | JCL_MGMTCLAS | JCL_MODIFY | JCL_MSGCLASS | JCL_MSGLEVEL
    | JCL_NAME | JCL_NOTIFY | JCL_NULLFILE
    | JCL_OFFSET | JCL_OPTCD | JCL_OUTBIN | JCL_OUTDISP | JCL_OUTLIM | JCL_OUTPUT | JCL_OVERLAY | JCL_OVFL
    | JCL_PAGEDEF | JCL_PAGES | JCL_PARM | JCL_PASSWORD | JCL_PATH | JCL_PATHDISP | JCL_PATHMODE | JCL_PATHOPTS | JCL_PEND
    | JCL_PERFORM | JCL_PGM | JCL_PIMSG | JCL_PRMODE | JCL_PROC | JCL_PROTECT | JCL_PRTERROR | JCL_PRTNO | JCL_PRTOPTNS | JCL_PRTQUEUE | JCL_PRTSP | JCL_PRTY
    | JCL_QNAME
    | JCL_RD | JCL_RECFM | JCL_RECORG | JCL_REF | JCL_REFDD | JCL_REGION | JCL_RESFMT | JCL_RESTART | JCL_RETAIN | JCL_RETRY | JCL_RETPD | JCL_RLS | JCL_ROOM
    | JCL_SCHENV | JCL_SECLABEL | JCL_SECMODEL | JCL_SEGMENT | JCL_SER | JCL_SORTCKPT | JCL_SPIN | JCL_SPACE | JCL_STEPCAT | JCL_STEPLIB
    | JCL_STORCLAS | JCL_STRNO | JCL_SUBSYS | JCL_SYNAD | JCL_SYMNAMES | JCL_SYSABEND | JCL_SYSAREA | JCL_SYSCHK | JCL_SYSCKEOV | JCL_SYSIN
    | JCL_SYSMDUMP | JCL_SYSOUT | JCL_SYSUDUMP
    | JCL_TERM | JCL_THRESHLD | JCL_TIME | JCL_TITLE | JCL_TRC | JCL_TRTCH | JCL_TYPRUN
    | JCL_UNIT | JCL_USER | JCL_USERDATA | JCL_USERLIB
    | JCL_VIO | JCL_VOL
    | JCL_WRITER
    | JCL_XMIT
    | JCL_ASTERISK_CHAR
    ;

// parameter names
JCL_ACCODE : 'ACCODE';
JCL_ACCT : 'ACCT';
JCL_ADDRESS : 'ADDRESS';
JCL_ADDRSPC : 'ADDRSPC';
JCL_AFF : 'AFF';
JCL_AMP : 'AMP';
JCL_AVGREC : 'AVGREC';
JCL_BLKSIZE : 'BLKSIZE';
JCL_BLKSZLIM : 'BLKSZLIM';
JCL_BUFND : 'BUFND';
JCL_BUFNI : 'BUFNI';
JCL_BUFNO : 'BUFNO';
JCL_BUFSP : 'BUFSP';
JCL_BUILDING : 'BUILDING';
JCL_BURST : 'BURST';
JCL_BYTES : 'BYTES';
JCL_CCSID : 'CCSID';
JCL_CHARS : 'CHARS';
JCL_CHKPT : 'CHKPT';
JCL_CKPTLINE : 'CKPTLINE';
JCL_CKPTPAGE : 'CKPTPAGE';
JCL_CKPTSEC : 'CKPTSEC';
JCL_CLASS :'CLASS';
JCL_COLORMAP : 'COLORMAP';
JCL_COMMAND : 'COMMAND';
JCL_COMPACT : 'COMPACT';
JCL_COMSETUP : 'COMSETUP';
JCL_COND : 'COND';
JCL_CONTROL : 'CONTROL';
JCL_COPIES : 'COPIES';
JCL_CROPS : 'CROPS';
JCL_DATA : 'DATA';
JCL_DATACK : 'DATACK';
JCL_DATACLAS : 'DATACLAS';
JCL_DCB : 'DCB';
JCL_DDNAME : 'DDNAME';
JCL_DEFAULT : 'DEFAULT';
JCL_DEN : 'DEN';
JCL_DEPT : 'DEPT';
JCL_DEST : 'DEST';
JCL_DISP : 'DISP';
JCL_DLM : 'DLM';
JCL_DPAGELBL : 'DPAGELBL';
JCL_DSN : 'DSN';
JCL_DSNTYPE : 'DSNTYPE';
JCL_DSORG : 'DSORG';
JCL_DUMMY : 'DUMMY';
JCL_DUPLEX : 'DUPLEX';
JCL_DYNAMNBR : 'DYNAMNBR';
JCL_EXPDT : 'EXPDT';
JCL_FCB : 'FCB';
JCL_FILEDATA : 'FILEDATA';
JCL_FLASH : 'FLASH';
JCL_FORMDEF : 'FORMDEF';
JCL_FORMLEN : 'FORMLEN';
JCL_FORMS : 'FORMS';
JCL_FREE : 'FREE';
JCL_GROUP : 'GROUP';
JCL_GROUPID : 'GROUPID';
JCL_HOLD : 'HOLD';
JCL_INDEX : 'INDEX';
JCL_JESDS : 'JESDS';
JCL_JOBCAT : 'JOBCAT';
JCL_JOBLIB : 'JOBLIB';
JCL_KEYOFF : 'KEYOFF';
JCL_LABEL : 'LABEL';
JCL_LGSTREAM : 'LGSTREAM';
JCL_LIKE : 'LIKE';
JCL_LINDEX : 'LINDEX';
JCL_LINECT : 'LINECT';
JCL_LINES : 'LINES';
JCL_LRECL : 'LRECL';
JCL_MEMLIMIT : 'MEMLIMIT';
JCL_MGMTCLAS : 'MGMTCLAS';
JCL_MODIFY : 'MODIFY';
JCL_MSGCLASS : 'MSGCLASS';
JCL_MSGLEVEL : 'MSGLEVEL';
JCL_NAME : 'NAME';
JCL_NULLFILE : 'NULLFILE';
JCL_OFFSET : 'OFFSET';
JCL_OPTCD : 'OPTCD';
JCL_OUTBIN : 'OUTBIN';
JCL_OUTDISP : 'OUTDISP';
JCL_OUTLIM : 'OUTLIM';
JCL_OVERLAY : 'OVERLAY';
JCL_OVFL : 'OVFL';
JCL_PAGEDEF : 'PAGEDEF';
JCL_PAGES : 'PAGES';
JCL_PARM : 'PARM';
JCL_PASSWORD : 'PASSWORD';
JCL_PATH : 'PATH';
JCL_PATHDISP : 'PATHDISP';
JCL_PATHMODE : 'PATHMODE';
JCL_PATHOPTS : 'PATHOPTS';
JCL_PERFORM : 'PERFORM';
JCL_PGM : 'PGM';
JCL_PIMSG : 'PIMSG';
JCL_PRMODE : 'PRMODE';
JCL_PROTECT : 'PROTECT';
JCL_PRTERROR : 'PRTERROR';
JCL_PRTNO : 'PRTNO';
JCL_PRTOPTNS : 'PRTOPTNS';
JCL_PRTQUEUE : 'PRTQUEUE';
JCL_PRTSP : 'PRTSP';
JCL_PRTY : 'PRTY';
JCL_QNAME : 'QNAME';
JCL_RD : 'RD';
JCL_RECFM : 'RECFM';
JCL_RECORG : 'RECORG';
JCL_REF : 'REF';
JCL_REFDD : 'REFDD';
JCL_REGION : 'REGION';
JCL_RESFMT : 'RESFMT';
JCL_RESTART : 'RESTART';
JCL_RETAIN : 'RETAIN';
JCL_RETRY : 'RETRY';
JCL_RETPD : 'RETPDD';
JCL_RLS : 'RLS';
JCL_ROOM : 'ROOM';
JCL_SCHENV : 'SCHENV';
JCL_SECLABEL : 'SECLABEL';
JCL_SECMODEL :'SECMODEL';
JCL_SEGMENT : 'SEGMENT';
JCL_SER : 'SER';
JCL_SORTCKPT : 'SORTCKPT';
JCL_SPIN : 'SPIN';
JCL_SPACE : 'SPACE';
JCL_STEPCAT : 'STEPCAT';
JCL_STEPLIB : 'STEPLIB';
JCL_STORCLAS : 'STORCLAS';
JCL_STRNO : 'STRNO';
JCL_SUBSYS : 'SUBSYS';
JCL_SYNAD : 'SYNAD';
JCL_SYMNAMES : 'SYMNAMES';
JCL_SYSABEND : 'SYSABEND';
JCL_SYSAREA : 'SYSAREA';
JCL_SYSCHK : 'SYSCHK';
JCL_SYSCKEOV : 'SYSCKEOV';
JCL_SYSIN : 'SYSIN';
JCL_SYSMDUMP : 'SYSMDUMP';
JCL_SYSOUT : 'SYSOUT';
JCL_SYSUDUMP : 'SYSUDUMP';
JCL_TERM : 'TERM';
JCL_THRESHLD : 'THRESHLD';
JCL_TIME : 'TIME';
JCL_TITLE : 'TITLE';
JCL_TRC : 'TRC';
JCL_TRTCH : 'TRTCH';
JCL_TYPRUN : 'TYPRUN';
JCL_UNIT : 'UNIT';
JCL_USER : 'USER';
JCL_USERDATA : 'USERDATA';
JCL_USERLIB : 'USERLIB';
JCL_VIO : 'VIO';
JCL_VOL : 'VOL';
JCL_WRITER :'WRITER';

// symbols
JCL_EQUAL_CHAR : '=';
JCL_L_BRACE_CHAR : '{';
JCL_R_BRACE_CHAR : '}';

JCL_L_BRACKET_CHAR : '[';
JCL_R_BRACKET_CHAR : ']';

JCL_L_PAREN_CHAR : '(';
JCL_R_PAREN_CHAR : ')';

JCL_AMPERSAND_CHAR : '&';
JCL_ASTERISK_CHAR : '*';
JCL_PLUS_CHAR : '+';
JCL_MINUS_CHAR : '-';

JCL_SINGLEQUOTE_CHAR : '\'';
JCL_SINGLEQUOTEFANCY_CHAR : '’';
JCL_DOUBLEQUOTE_CHAR : '"';

JCL_PERIOD_CHAR : '.';
JCL_COMMA_CHAR : ',';
JCL_DOUBLE_SLASH : '//';

JCL_STRINGLITERAL : STRINGLITERAL;

// names
JCL_NAME_FIELD : JCL_NAME_CHAR ((JCL_PERIOD_CHAR JCL_NAME_CHAR)+)?;
JCL_NAME_CHAR : ([a-zA-Z0-9$#_@&%.-]+ | JCL_ASTERISK_CHAR);

mode IF_CONDITION;
IF_CONDITION_WS : WS -> type(WS), channel(HIDDEN);
IF_CONDITION_THEN : 'THEN' -> popMode;

IF_CONDITION_CA_START : CA_START;

IF_CONDITION_STRINGLITERAL : STRINGLITERAL;
IF_CONDITION_TEXT : TEXT;

mode INSIDE_STREAM;
STREAM_WS : WS -> type(WS), channel(HIDDEN);
STREAM_EOL : EOL -> type(EOL), channel(HIDDEN), popMode;

STREAM_CA_START : CA_START;

STREAM_STRINGLITERAL : STRINGLITERAL;
STREAM_TEXT : TEXT;

mode INSIDE_JES2;
JES2_WS : WS -> type(WS), channel(HIDDEN);
JES2_EOL : EOL -> type(EOL), channel(HIDDEN), popMode;

JES2_CA_START : CA_START -> type(CA_START);

JES2_STRINGLITERAL : STRINGLITERAL;
JES2_TEXT : TEXT;

mode INSIDE_JES3;
JES3_WS : WS -> type(WS), channel(HIDDEN);
JES3_EOL : EOL -> type(EOL), channel(HIDDEN), popMode;

JES3_CA_START : CA_START -> type(CA_START);

JES3_STRINGLITERAL : STRINGLITERAL;
JES3_TEXT : TEXT;

mode INSIDE_CM;
CM_WS : WS -> type(WS), channel(HIDDEN);
CM_EOL : EOL -> type(EOL), channel(HIDDEN), popMode;

CM_CA_START : CA_START -> type(CA_START);

CM_STRINGLITERAL : STRINGLITERAL;
CM_TEXT : TEXT;

mode INSIDE_TRAILING_COMMENT;
// JCL whitespace rules do not apply.
TRAILING_COMMENT_WS : [ \t\f]+ -> channel(HIDDEN);
TRAILING_COMMENT_EOL : EOL -> type(EOL), channel(HIDDEN), popMode;
TRAILING_COMMENT_STOP : '^^TC_STOP^^' -> skip, popMode;

TRAILING_COMMENT_STRINGLITERAL : STRINGLITERAL;
TRAILING_COMMENT_TEXT : TEXT;

mode INSIDE_COMMENT;
// JCL whitespace rules do not apply.
COMMENT_WS : [ \t\f]+ -> channel(HIDDEN);
COMMENT_EOL : EOL -> type(EOL), channel(HIDDEN), popMode;

COMMENT_CA_START : CA_START -> type(CA_START);

COMMENT_STRINGLITERAL : STRINGLITERAL;
COMMENT_TEXT : TEXT;

mode INSIDE_UNKNOWN;
// JCL whitespace rules do not apply.
UNKNOWN_WS : [ \t\f]+ -> channel(HIDDEN);
UNKNOWN_EOL : EOL -> type(EOL), channel(HIDDEN), popMode;

UNKNOWN_CA_START : CA_START -> type(CA_START);

UNKNOWN_STRINGLITERAL : STRINGLITERAL;
UNKNOWN_TEXT : TEXT;