/*
 * For commercial customers of Moderne Inc., this repository is licensed per the terms of our contract.
 * For everyone else, this is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
 * See: https://creativecommons.org/licenses/by-nc-sa/4.0/
 */
lexer grammar ControlMLexer;

UTF_8_BOM : '\uFEFF' -> skip;

WS : [ \t\f]+ -> channel(HIDDEN);
EOL : (CR? LF | FORM_FEED) -> channel(HIDDEN);

DEFINITION_START :  '<<DEFINITION_START>>' -> skip, pushMode(DEFINITION);
SCHEDULE_START : '<<SCHEDULE_START>>' -> skip, pushMode(SCHEDULE);
INPUT_START : '<<INPUT_START>>' -> skip, pushMode(INPUT);
OUTPUT_START : '<<OUTPUT_START>>' -> skip, pushMode(OUTPUT);
APP_FORM_START : '<<APP_FORM_START>>' -> skip, pushMode(APP_FORM);

LINE_START : '<<LINE_START>>|';
LINE_END : '|<<LINE_END>>';

SECTION_HEADER : '| =========================================================================== |';

ODAT : 'ODAT';
DATE_WILDCARD : '****';

NAME : ~[ \r\n]+;

fragment LF : '\n';
fragment CR : '\r';
fragment FORM_FEED : '\u000C';

mode DEFINITION;
DEFINITION_END : '<<DEFINITION_END>>' -> skip, popMode;
DEFINITION_WS : WS -> channel(HIDDEN);
DEFINITION_EOL : EOL -> channel(HIDDEN);

DEFINITION_HEADER : '+---------------------------------- BROWSE -----------------------------------+';
DEFINITION_LINE_START : LINE_START;
DEFINITION_LINE_END : LINE_END;

DEFINITION_APPL : 'APPL';
DEFINITION_AT : 'AT';
DEFINITION_CTB_STEP : 'CTB STEP';
DEFINITION_DESC : 'DESC';
DEFINITION_DFLT : 'DFLT';
DEFINITION_DOCLIB : 'DOCLIB';
DEFINITION_DOCMEM : 'DOCMEM';
DEFINITION_GROUP : 'GROUP';
DEFINITION_MEMNAME : 'MEMNAME';
DEFINITION_MEMLIB : 'MEMLIB';
DEFINITION_NJE_NODE : 'NJE NODE';
DEFINITION_OWNER : 'OWNER';
DEFINITION_OVERLIB : 'OVERLIB';
DEFINITION_PREVENT_NCT2 : 'PREVENT-NCT2';
DEFINITION_SCHENV : 'SCHENV';
DEFINITION_SET_VAR : 'SET VAR';
DEFINITION_STAT_CAL : 'STAT CAL';
DEFINITION_SYSTEM_ID : 'SYSTEM ID';
DEFINITION_TASKTYPE : 'TASKTYPE';
DEFINITION_TYPE : 'TYPE';

DEFINITION_EQUALS_CHAR : '=';

DS_NAME : NAME -> type(NAME);

mode SCHEDULE;
SCHEDULE_END : '<<SCHEDULE_END>>' -> skip, popMode;
SCHEDULE_WS : WS -> channel(HIDDEN);
SCHEDULE_EOL : EOL -> channel(HIDDEN);

SCHEDULE_HEADER : SECTION_HEADER;
SCHEDULE_LINE_START : LINE_START;
SCHEDULE_LINE_END : LINE_END;

SCHEDULE_NAME : NAME -> type(NAME);

mode INPUT;
INPUT_END : '<<INPUT_END>>' -> skip, popMode;
INPUT_NAMES_START : '<<INPUT_NAMES_START>>' -> skip, pushMode(INPUT_NAMES);

INPUT_WS : WS -> channel(HIDDEN);
INPUT_EOL : EOL -> channel(HIDDEN);

INPUT_HEADER : SECTION_HEADER;
INPUT_LINE_START : LINE_START;
INPUT_LINE_END : LINE_END;

INPUT_NAME : NAME -> type(NAME);

mode INPUT_NAMES;
INPUT_NAMES_END : '<<INPUT_NAMES_END>>' -> skip, popMode;
INPUT_NAMES_WS : WS -> channel(HIDDEN);
INPUT_NAMES_EOL : EOL -> channel(HIDDEN);

INPUT_NAMES_IN : 'IN';
INPUT_NAMES_LINE_START : LINE_START;
INPUT_NAMES_LINE_END : LINE_END;

INPUT_NAMES_ODAT : ODAT -> type(ODAT);
INPUT_NAMES_DATE_WILDCARD : DATE_WILDCARD -> type(DATE_WILDCARD);
INPUT_NAMES_NAME : NAME -> type(NAME);

mode OUTPUT;
OUTPUT_END : '<<OUTPUT_END>>' -> skip, popMode;
OUTPUT_NAMES_START : '<<OUTPUT_NAMES_START>>' -> skip, pushMode(OUTPUT_NAMES);
OUTPUT_WS : WS -> channel(HIDDEN);
OUTPUT_EOL : EOL -> channel(HIDDEN);

OUTPUT_HEADER : SECTION_HEADER;
OUTPUT_LINE_START : LINE_START;
OUTPUT_LINE_END : LINE_END;

OUTPUT_NAME : NAME -> type(NAME);

mode OUTPUT_NAMES;
OUTPUT_NAMES_END : '<<OUTPUT_NAMES_END>>' -> skip, popMode;
OUTPUT_NAMES_WS : WS -> channel(HIDDEN);
OUTPUT_NAMES_EOL : EOL -> channel(HIDDEN);

OUTPUT_NAMES_OUT : 'OUT';
OUTPUT_NAMES_LINE_START : LINE_START;
OUTPUT_NAMES_LINE_END : LINE_END;

OUTPUT_NAMES_ODAT : ODAT -> type(ODAT);
OUTPUT_NAMES_DATE_WILDCARD : DATE_WILDCARD -> type(DATE_WILDCARD);
OUTPUT_NAMES_NAME : NAME -> type(NAME);

mode APP_FORM;
APP_FORM_END : '<<APP_FORM_END>>' -> skip, popMode;
APP_FORM_WS : WS -> channel(HIDDEN);
APP_FORM_EOL : EOL -> channel(HIDDEN);

APP_FORM_SECTION_HEADER : SECTION_HEADER -> type(SECTION_HEADER);
APP_FORM_LINE_START : LINE_START;
APP_FORM_LINE_END : LINE_END;

APP_FORM_NAME : NAME -> type(NAME);
