/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.assembler.trait;

import lombok.Value;
import org.jspecify.annotations.Nullable;
import org.openrewrite.Cursor;
import org.openrewrite.assembler.tree.Assembler;
import org.openrewrite.trait.SimpleTraitMatcher;
import org.openrewrite.trait.Trait;

import java.util.ArrayList;
import java.util.List;

import static java.util.Collections.singletonList;

/**
 * A name this member offers to whatever calls it: the control section it assembles into, an
 * {@code ENTRY} it declares besides that, or the name its {@code END} gives as where control begins.
 * <p>
 * These are the names a caller writes. A COBOL {@code CALL 'CLMU030'} and an {@code INCLUDE
 * OBJLIB(CLMU030)} both reach {@code asm/CLMU030} because it offers that name — and it offers it on
 * its {@code END}, since the {@code CSECT} is generated by the shop's entry macro and never written in
 * the program at all.
 */
@Value
public class EntryPoint implements Trait<Assembler.Instruction> {

    Cursor cursor;

    public Kind getKind() {
        String operation = getTree().getOperation().getUpperText();
        if ("ENTRY".equals(operation)) {
            return Kind.ENTRY;
        }
        return "END".equals(operation) ? Kind.END : Kind.SECTION;
    }

    /**
     * The names offered. A section or an {@code END} names one; an {@code ENTRY} may name several.
     */
    public List<String> getNames() {
        if (getKind() == Kind.SECTION) {
            return singletonList(getTree().getSimpleName());
        }
        List<String> names = new ArrayList<>(getTree().getOperandTexts());
        names.removeIf(String::isEmpty);
        return names;
    }

    public int getLine() {
        return Statements.lineOf(cursor, getTree().getOperation());
    }

    /**
     * Where the name was written, which says what kind of name it is.
     */
    public enum Kind {
        /**
         * The label of a {@code CSECT}, {@code RSECT} or {@code START}: the section itself.
         */
        SECTION,
        /**
         * An {@code ENTRY} statement, which offers a name part way into a section.
         */
        ENTRY,
        /**
         * The operand of the {@code END}, which is where control begins when the module is given it.
         */
        END
    }

    public static class Matcher extends SimpleTraitMatcher<EntryPoint> {

        @Override
        protected @Nullable EntryPoint test(Cursor cursor) {
            Object value = cursor.getValue();
            if (!(value instanceof Assembler.Instruction)) {
                return null;
            }
            Assembler.Instruction instruction = (Assembler.Instruction) value;
            String operation = instruction.getOperation().getUpperText();
            if ("ENTRY".equals(operation) || "END".equals(operation)) {
                String name = instruction.getOperandText(0);
                return name == null || Statements.isVariable(name) ? null : new EntryPoint(cursor);
            }
            boolean section = "CSECT".equals(operation) || "RSECT".equals(operation) ||
                              "START".equals(operation);
            return section && !instruction.getSimpleName().isEmpty() &&
                   !Statements.isVariable(instruction.getSimpleName()) ? new EntryPoint(cursor) : null;
        }
    }

    @Override
    public String toString() {
        return getKind() + " " + getNames();
    }
}
