---
name: ci

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 18 * * *

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_SWITCHES: --console=plain --info --stacktrace --warning-mode=all --no-daemon

jobs:
  build:
    steps:
      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ env.GRADLE_SWITCHES }} integTest
